In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('Database_for_dimensionality_reduction.csv')
dfcopy = df.copy()
dfcopy1= df.select_dtypes(include=[np.number])
dfcopy1.head()

Latitude  Longitude  Absolute elevation  Distance from Coast     AP1  \
0     24.60      72.72              1195.0               253.94     NaN   
1     10.33      79.38                 6.0                 2.56  1013.9   
2     23.88      91.25                16.0               124.39  1015.2   
3     10.85      72.47                 4.0                 0.00  1012.3   
4     27.17      78.03               169.0               751.48   997.0   

      AP2   DT1   DT2   HTM   LTM  AC1  AC2  LC1  LC2   RFL   RH1   RH2  WSD  
0     NaN   8.7  16.3  23.4  -0.7  0.8  1.0  0.4  0.5   3.7  61.0  42.0  2.0  
1  1010.4  23.5  27.1  31.9  18.2  3.2  3.4  1.3  1.4  34.5  87.0  70.0  6.7  
2  1011.8  16.8  16.5  28.8   6.4  1.5  1.5  0.4  0.3   5.6  81.0  66.0  2.3  
3  1009.5  26.2  28.7  32.0  22.2  3.1  3.9  2.5  2.9   5.0  81.0  71.0  NaN  
4   995.2  10.7  19.8  27.3   4.2  1.3  1.6  0.4  0.4   9.5  77.0  55.0  1.9

In [3]:
for column in dfcopy1: 
        meani = dfcopy[column].mean()
        dfcopy1[column].fillna(meani, inplace=True)
dfcopy1.head()

Latitude  Longitude  Absolute elevation  Distance from Coast          AP1  \
0     24.60      72.72              1195.0               253.94   981.133938   
1     10.33      79.38                 6.0                 2.56  1013.900000   
2     23.88      91.25                16.0               124.39  1015.200000   
3     10.85      72.47                 4.0                 0.00  1012.300000   
4     27.17      78.03               169.0               751.48   997.000000   

           AP2   DT1   DT2   HTM   LTM  AC1  AC2  LC1  LC2   RFL   RH1   RH2  \
0   978.160215   8.7  16.3  23.4  -0.7  0.8  1.0  0.4  0.5   3.7  61.0  42.0   
1  1010.400000  23.5  27.1  31.9  18.2  3.2  3.4  1.3  1.4  34.5  87.0  70.0   
2  1011.800000  16.8  16.5  28.8   6.4  1.5  1.5  0.4  0.3   5.6  81.0  66.0   
3  1009.500000  26.2  28.7  32.0  22.2  3.1  3.9  2.5  2.9   5.0  81.0  71.0   
4   995.200000  10.7  19.8  27.3   4.2  1.3  1.6  0.4  0.4   9.5  77.0  55.0   

       WSD  
0  2.00000  
1  6.70000  
2  2.30000  
3  4.79115  
4  1.90000

In [4]:
df_act = dfcopy1[["AP1","AP2","DT1","DT2","HTM","LTM","AC1","AC2","LC1","LC2","RFL","RH1","RH2","WSD"]]
df_act.head()

AP1          AP2   DT1   DT2   HTM   LTM  AC1  AC2  LC1  LC2   RFL  \
0   981.133938   978.160215   8.7  16.3  23.4  -0.7  0.8  1.0  0.4  0.5   3.7   
1  1013.900000  1010.400000  23.5  27.1  31.9  18.2  3.2  3.4  1.3  1.4  34.5   
2  1015.200000  1011.800000  16.8  16.5  28.8   6.4  1.5  1.5  0.4  0.3   5.6   
3  1012.300000  1009.500000  26.2  28.7  32.0  22.2  3.1  3.9  2.5  2.9   5.0   
4   997.000000   995.200000  10.7  19.8  27.3   4.2  1.3  1.6  0.4  0.4   9.5   

    RH1   RH2      WSD  
0  61.0  42.0  2.00000  
1  87.0  70.0  6.70000  
2  81.0  66.0  2.30000  
3  81.0  71.0  4.79115  
4  77.0  55.0  1.90000

## scaling

In [5]:
sc= StandardScaler()
df_scale = sc.fit_transform(df_act)
df_scale = pd.DataFrame(df_scale, columns = df_act.columns)
df_scale.head()

AP1           AP2       DT1       DT2       HTM       LTM       AC1  \
0  0.000000 -2.727827e-15 -1.276985 -1.097900 -1.221526 -1.489278 -1.138579   
1  0.772602  7.735684e-01  1.310352  0.776498  0.608600  1.561643  1.208692   
2  0.803255  8.071603e-01  0.139058 -1.063189 -0.058858 -0.343165 -0.453958   
3  0.734875  7.519736e-01  1.782367  1.054186  0.630130  2.207341  1.110889   
4  0.374111  4.088563e-01 -0.927345 -0.490456 -0.381821 -0.698298 -0.649564   

        AC2       LC1       LC2       RFL       RH1       RH2       WSD  
0 -0.966943 -0.697620 -0.523512 -0.479262 -1.292516 -0.886205 -1.053900  
1  1.256700  0.591070  0.641758  0.616722  1.460395  1.181177  0.720755  
2 -0.503684 -0.697620 -0.782460 -0.411652  0.825108  0.885837 -0.940624  
3  1.719959  2.309324  2.583873 -0.433003  0.825108  1.255013  0.000000  
4 -0.411032 -0.697620 -0.652986 -0.272875  0.401583  0.073651 -1.091658

## splitting into label and feature

In [6]:
Y_label = df_scale["AP1"]
Y_label[:5]

0    0.000000
1    0.772602
2    0.803255
3    0.734875
4    0.374111
Name: AP1, dtype: float64

In [7]:
df_scale.drop("AP1", axis = 1, inplace = True)
X_label = df_scale
#X_label.head()

In [8]:
X_label.head()

AP2       DT1       DT2       HTM       LTM       AC1       AC2  \
0 -2.727827e-15 -1.276985 -1.097900 -1.221526 -1.489278 -1.138579 -0.966943   
1  7.735684e-01  1.310352  0.776498  0.608600  1.561643  1.208692  1.256700   
2  8.071603e-01  0.139058 -1.063189 -0.058858 -0.343165 -0.453958 -0.503684   
3  7.519736e-01  1.782367  1.054186  0.630130  2.207341  1.110889  1.719959   
4  4.088563e-01 -0.927345 -0.490456 -0.381821 -0.698298 -0.649564 -0.411032   

        LC1       LC2       RFL       RH1       RH2       WSD  
0 -0.697620 -0.523512 -0.479262 -1.292516 -0.886205 -1.053900  
1  0.591070  0.641758  0.616722  1.460395  1.181177  0.720755  
2 -0.697620 -0.782460 -0.411652  0.825108  0.885837 -0.940624  
3  2.309324  2.583873 -0.433003  0.825108  1.255013  0.000000  
4 -0.697620 -0.652986 -0.272875  0.401583  0.073651 -1.091658

# SVD

In [9]:
U, S, Vt = np.linalg.svd(X_label)

In [10]:
S

array([ 48.50119431,  35.67854355,  24.39492154,  18.93786092,
        15.93780367,  14.61732492,  12.45247485,   9.26500338,
         7.32264817,   5.59523276,   5.27411081,   3.47500462,   2.91839142])

In [11]:
# Cum = S/S.sum()*100
# Cum = Cum.cumsum()
# k=0
# for i in range(len(Cum)):
#     if (Cum[i] >= 90):
#         k = i;
#         break
# k, Cum

(8, array([  23.73199203,   41.18976649,   53.12638149,   62.39281648,
          70.19130135,   77.34366622,   83.43675399,   87.97018846,
          91.55321421,   94.29100286,   96.87166417,   98.57200956,  100.        ]))

In [12]:
k = 5

In [44]:
S1 = np.zeros((X_label.shape[0], X_label.shape[1]))
S1[:X_label.shape[1], :X_label.shape[1]] = np.diag(S)

In [45]:
S1.shape

(417, 13)

In [15]:
Vt.shape,U.shape

((13, 13), (417, 417))

In [46]:
Vt1 = Vt[:5,:]
S11 = S1[:,:5]
S11.shape, Vt1.shape

((417, 5), (5, 13))

In [59]:
X_label_Reconstruct = U.dot(S11.dot(Vt1))

In [60]:
X_label_Reconstruct = pd.DataFrame(X_label_Reconstruct, columns = X_label.columns)
X_label_Reconstruct.head()

AP2       DT1       DT2       HTM       LTM       AC1       AC2  \
0 -0.599188 -1.466125 -0.896661 -0.739644 -1.607098 -1.120000 -1.014228   
1  1.009082  1.356798  0.684030  0.554271  1.527380  1.241604  1.027112   
2  0.839071 -0.360539 -0.391750 -0.273301 -0.370274 -0.519934 -0.704009   
3  0.099262  1.808625  1.188668  0.864234  1.983415  1.915838  1.895195   
4  0.300064 -0.746383 -0.487165 -0.372849 -0.815226 -0.652689 -0.734225   

        LC1       LC2       RFL       RH1       RH2       WSD  
0 -0.896258 -0.743475 -0.079042 -0.739403 -0.845989 -0.834809  
1  1.002498  0.686315  0.425190  1.168000  1.225681  0.668955  
2 -0.434237 -0.711615 -0.378663  1.088139  0.733362 -0.660663  
3  1.813288  1.728677 -0.212286  1.413143  1.060334  0.158488  
4 -0.487817 -0.619378 -0.198148  0.484056  0.048562 -1.030800

In [68]:
X_label_Transformed = X_label_Reconstruct.dot(Vt1.T)
X_label_Transformed.head()

0         1         2         3         4
0  0.098637  3.466396  0.090657  0.095351  0.064083
1 -0.522637 -3.537994 -0.791520  0.039084 -0.340500
2  0.276852  0.772425 -2.048505  0.078149  0.293546
3 -1.202745 -4.733389  0.031446 -1.457069  0.359363
4  0.110755  1.706241 -1.268189 -0.278659  0.061246

# SVD MATHEMATICAL

In [19]:
temp1 = (X_label.T).dot(X_label)
temp2 = (X_label).dot(X_label.T)

In [20]:
temp1.shape, temp2.shape

((13, 13), (417, 417))

In [21]:
eigval_V, eigvec_V = np.linalg.eig(temp1)
eigval_U, eigvec_U = np.linalg.eig(temp2)

In [22]:
eigvec_U.shape, eigvec_V.shape

((417, 417), (13, 13))

In [29]:
temp3 = eigval_V**0.5

In [31]:
Sigma = np.zeros((X_label.shape[0], X_label.shape[1]))
Sigma[:X_label.shape[1], :X_label.shape[1]] = np.diag(temp3)
Sigma.shape

(417, 13)

In [82]:
# we can see that S ans Sigma are same....
#we will take k = 5
Vt_m = eigvec_V.T[:5,:]
Sigma = Sigma[:,:5]
Sigma.shape, V_m.shape

((417, 5), (5, 13))

In [95]:
eigvec_U[:1,:20].real

array([[-0.0020337 ,  0.09715631, -0.00371624,  0.00503492, -0.00402082,
        -0.00427098,  0.08224438, -0.00272335, -0.01349167,  0.05632923,
        -0.06688143,  0.0043238 ,  0.00669733,  0.03704259,  0.03704259,
        -0.08869146, -0.02337623, -0.01915583, -0.00699119, -0.00699119]])

In [96]:
U[:1,:20]

array([[ 0.0020337 ,  0.09715631,  0.00371624,  0.00503492,  0.00402082,
        -0.00427098,  0.08224438,  0.00272335, -0.01349167, -0.05632923,
         0.06688143, -0.0043238 ,  0.00669733,  0.02080789, -0.00047901,
         0.03596977, -0.00386774,  0.01024704, -0.03441978,  0.03571371]])

In [99]:
X_label_Recon_m = (eigvec_U).dot(Sigma.dot(Vt_m))
X_label_Recon_m = pd.DataFrame(X_label_Recon_m.real, columns = X_label.columns)
X_label_Recon_m.head()

AP2       DT1       DT2       HTM       LTM       AC1       AC2  \
0 -0.583766 -1.512906 -0.933544 -0.783708 -1.652933 -1.059603 -0.965055   
1  0.428577  1.691008  1.237144  1.068706  1.802544  1.040276  0.992377   
2 -1.336435 -0.310638 -0.070051 -0.135345 -0.358761 -0.023878  0.263646   
3  1.142013  2.247499  1.224127  1.105194  2.464031  0.967417  0.808627   
4 -0.907205 -0.720747 -0.419445 -0.384340 -0.789713 -0.426345 -0.239951   

        LC1       LC2       RFL       RH1       RH2       WSD  
0 -0.806769 -0.679239 -0.068770 -0.563573 -0.778976 -1.050718  
1  0.755537  0.711288  0.163669  0.056233  0.290203  1.145250  
2  0.034614  0.449913 -0.098912 -1.271225 -0.950649  0.352447  
3  0.479990  0.302577 -0.297361  0.537710  1.390284  2.595334  
4 -0.352594 -0.075031  0.078100 -1.114003 -0.833005  0.114606

In [101]:
X_label_Trans_m = X_label_Recon_m.dot(Vt_m.T)
X_label_Trans_m.head()

0         1         2         3         4
0 -0.098637  3.466396 -0.090657  0.095351 -0.064083
1  0.522637 -3.537994  0.791520  0.039084  0.340500
2 -0.276852  0.772425  2.048505  0.078149 -0.293546
3  1.202745 -4.733389 -0.031446 -1.457069 -0.359363
4 -0.110755  1.706241  1.268189 -0.278659 -0.061246

## SVD with SKlearn

In [65]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=5)
svd.fit(X_label)
result = svd.transform(X_label)
result = pd.DataFrame(result)

0         1         2         3         4
0 -0.098637 -3.466396  0.090657  0.095351 -0.064083
1  0.522637  3.537994 -0.791520  0.039084  0.340500
2 -0.276852 -0.772425 -2.048505  0.078149 -0.293546
3  1.202745  4.733389  0.031446 -1.457069 -0.359363
4 -0.110755 -1.706241 -1.268189 -0.278659 -0.061246

# The Results Compared

In [103]:
result.head()   #This is TruncatedSVD sklearn lib result

0         1         2         3         4
0 -0.098637 -3.466396  0.090657  0.095351 -0.064083
1  0.522637  3.537994 -0.791520  0.039084  0.340500
2 -0.276852 -0.772425 -2.048505  0.078149 -0.293546
3  1.202745  4.733389  0.031446 -1.457069 -0.359363
4 -0.110755 -1.706241 -1.268189 -0.278659 -0.061246

In [66]:
X_label_Transformed.head() #This is using numpy SVD 

0         1         2         3         4
0  0.098637  3.466396  0.090657  0.095351  0.064083
1 -0.522637 -3.537994 -0.791520  0.039084 -0.340500
2  0.276852  0.772425 -2.048505  0.078149  0.293546
3 -1.202745 -4.733389  0.031446 -1.457069  0.359363
4  0.110755  1.706241 -1.268189 -0.278659  0.061246

In [102]:
X_label_Trans_m.head()    #This is a Complete Mathematical Approch

0         1         2         3         4
0 -0.098637  3.466396 -0.090657  0.095351 -0.064083
1  0.522637 -3.537994  0.791520  0.039084  0.340500
2 -0.276852  0.772425  2.048505  0.078149 -0.293546
3  1.202745 -4.733389 -0.031446 -1.457069 -0.359363
4 -0.110755  1.706241  1.268189 -0.278659 -0.061246